<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Mach1.Orchestrator</AssemblyName>
    <RootNamespace>Mach1.Orchestrator</RootNamespace>
    <Version>1.4166.503</Version>
    <AssemblyVersion>1.4166.503.0</AssemblyVersion>
    <FileVersion>1.4166.503.0</FileVersion>
    <InformationalVersion>Mach1.04166.503.BF</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\scripts\WinReEngine.ps1" Link="Assets\WinReEngine.ps1" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\8ea7ee01-c6f3-486d-a48e-fef86e3fd233_removalai_preview.png" Link="Assets\Mach1Logo.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
