<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Mach1.Setup</AssemblyName>
    <RootNamespace>Mach1.Setup</RootNamespace>
    <Version>1.4166.501</Version>
    <AssemblyVersion>1.4166.501.0</AssemblyVersion>
    <FileVersion>1.4166.501.0</FileVersion>
    <InformationalVersion>Mach1.04166.501.CU</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload\payload.zip" LogicalName="Mach1.Setup.Payload.payload.zip" Condition="Exists('Payload\\payload.zip')" />
    <Resource Include="..\..\8ea7ee01-c6f3-486d-a48e-fef86e3fd233_removalai_preview.png" Link="Assets\Mach1Icon.png" />
  </ItemGroup>
</Project>
