<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Mach1.Setup</AssemblyName>
    <RootNamespace>Mach1.Setup</RootNamespace>
    <Version>1.4166.501</Version>
    <AssemblyVersion>1.4166.501.0</AssemblyVersion>
    <FileVersion>1.4166.501.0</FileVersion>
    <InformationalVersion>Mach1.04166.501.CU</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\scripts\WinReEngine.ps1" Link="Payload\WinReEngine.ps1" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
